# Generated by Django 4.0.5 on 2022-06-11 19:15

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', tinymce.models.HTMLField()),
                ('link', models.CharField(max_length=250)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('comment', models.CharField(blank=True, default='', max_length=250)),
                ('overall', models.IntegerField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField(blank=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
